# Generated by Django 5.0.7 on 2025-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('pressao', models.CharField(max_length=20)),
                ('urgencia', models.CharField(choices=[('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Vermelho', 'Vermelho')], max_length=10)),
            ],
        ),
    ]
