# Generated by Django 5.1.6 on 2025-02-21 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_hora_entrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
