# Generated by Django 5.1.6 on 2025-02-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paciente_urgencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='pressao',
        ),
        migrations.AddField(
            model_name='paciente',
            name='pressao_diastolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pressao_sistolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='urgencia',
            field=models.CharField(blank=True, choices=[('azul', 'Azul'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho')], max_length=10),
        ),
    ]
