# Generated by Django 5.1.6 on 2025-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_paciente_pressao_paciente_pressao_diastolica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
