# Generated by Django 5.1.6 on 2025-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paciente_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('atendimento', 'Atendimento'), ('evadiu', 'Evadiu'), ('alta', 'Alta')], default='aguardando', max_length=20),
        ),
    ]
