# Generated by Django 5.1.7 on 2025-03-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['urgencia', 'data_hora_entrada']},
        ),
    ]
